FROM python:3.8-slim

WORKDIR /app

# Copy the Python script
COPY app.py .

# Install Flask to serve the app
RUN pip install Flask

# Expose the required port
EXPOSE 80

# Run the application
CMD ["python", "app.py"]